#include "semantic.h"



//! note: All symbol table lookups should be preceded with a lookup to the global symbol table. 
//! this means we don't have to put pointers to the thing everywhere. Phew.




VarSymbolTableEntry make_vste(char * name, void * value, VarTypes type, int offset, int size, void * aux) {
    VarSymbolTableEntry vste;
    vste.name = name;
    vste.value = value;
    vste.type = type;
    vste.offset = offset;
    vste.size = size;
    vste.aux = aux;
    return vste;
}

int vst_insert(VarSymbolTable * st, VarSymbolTableEntry vste) {
    for (int i = 0; i < st->size; i++) {
        if (!strcmp(st->entries[i].name, vste.name)) {
            // Same type fine.
            if(st->entries[i].type == vste.type) {
                return 0;
            }
            return 1;
        }
    }

    if (st->size == st->capacity) {
        st->capacity = (int)(1.618 * st->capacity); // Hehe.
        st->entries = (VarSymbolTableEntry *)realloc(st->entries, st->capacity * sizeof(VarSymbolTableEntry));
    }
    st->entries[st->size++] = vste;
    
    return 0;
}

VarSymbolTableEntry * vst_lookup(VarSymbolTable * st, char * name) {
    for (int i = 0; i < st->size; i++) {
        if (!strcmp(st->entries[i].name, name)) {
            return &st->entries[i];
        }
    }
    return NULL;
}

VarSymbolTable make_vst() {
    VarSymbolTable st;
    st.size = 0;
    st.capacity = 69;
    st.entries = (VarSymbolTableEntry *)malloc(st.capacity * sizeof(VarSymbolTableEntry));
    return st;
}   

/// @brief Generated by the function prototype, modified by the function definition. 
/// That's why the ScopeTree is NULL. 
FunctionSymbolTableEntry make_fste(char * name, int numParams, VarSymbolTable * params) {
    FunctionSymbolTableEntry fste;
    fste.name = name;
    fste.numParams = numParams;
    fste.params = params;
    fste.locals = NULL;
    return fste;
}

FunctionSymbolTable make_fst() {
    FunctionSymbolTable fst;
    fst.size = 0;
    fst.capacity = 69;
    fst.entries = (FunctionSymbolTableEntry *)malloc(fst.capacity * sizeof(FunctionSymbolTableEntry));
    return fst;
}

int fst_insert(FunctionSymbolTable * fst, FunctionSymbolTableEntry fste) {
    for (int i = 0; i < fst->size; i++) {
        if (!strcmp(fst->entries[i].name, fste.name)) {
            return 1;
        }
    }

    if (fst->size == fst->capacity) {
        fst->capacity = (int)(1.618 * fst->capacity);
        fst->entries = (FunctionSymbolTableEntry *)realloc(fst->entries, fst->capacity * sizeof(FunctionSymbolTableEntry));
    }
    fst->entries[fst->size++] = fste;
    
    return 0;
}

Scope make_scope() {
    Scope s;
    s.vars = (VarSymbolTable *)malloc(sizeof(VarSymbolTable));
    *s.vars = make_vst();
    s.current = NULL;
    s.parent = NULL;
    s.children = (Scope **)calloc(1, sizeof(Scope *));
    return s;
}

ScopeTree make_scope_tree() {
    ScopeTree st;
    st.root = (Scope *)malloc(sizeof(Scope));
    *st.root = make_scope();
    return st;
}

/// @brief Provide the current scope and the current function.
VarSymbolTableEntry * scoped_lookup(FunctionSymbolTableEntry * func, Scope * s, char * name) {
    VarSymbolTableEntry * vste = vst_lookup(func->params, name);
    if(vste) {
        return vste;
    }
    Scope * current = s;
    while (current) {
        vste = vst_lookup(current->vars, name);
        if (vste) {
            return vste;
        }
        current = current->parent;
    }
    return NULL;
}

StructSymbolTable make_struct_st() {
    StructSymbolTable sst;
    sst.size = 0;
    sst.capacity = 69;
    sst.entries = (StructSymbolTableEntry *)malloc(sst.capacity * sizeof(StructSymbolTableEntry));
    return sst;
}

int sst_insert(StructSymbolTable * sst, StructSymbolTableEntry sste) {
    for (int i = 0; i < sst->size; i++) {
        if (!strcmp(sst->entries[i].name, sste.name)) {
            return 1;
        }
    }

    if (sst->size == sst->capacity) {
        sst->capacity = (int)(1.618 * sst->capacity);
        sst->entries = (StructSymbolTableEntry *)realloc(sst->entries, sst->capacity * sizeof(StructSymbolTableEntry));
    }
    sst->entries[sst->size++] = sste;
    
    return 0;
}

StructSymbolTableEntry * sst_lookup(StructSymbolTable * sst, char * name) {
    for (int i = 0; i < sst->size; i++) {
        if (!strcmp(sst->entries[i].name, name)) {
            return &sst->entries[i];
        }
    }
    return NULL;
}

EnumSymbolTableEntry make_enum_ste(char * name, char ** fields, int numFields) {
    EnumSymbolTableEntry este;
    este.name = name;
    este.fields = fields;
    este.numFields = numFields;
    return este;
}

EnumSymbolTable make_enum_st() {
    EnumSymbolTable est;
    est.size = 0;
    est.capacity = 69;
    est.entries = (EnumSymbolTableEntry *)malloc(est.capacity * sizeof(EnumSymbolTableEntry));
    return est;
}

int est_insert(EnumSymbolTable * est, EnumSymbolTableEntry este) {
    for (int i = 0; i < est->size; i++) {
        if (!strcmp(est->entries[i].name, este.name)) {
            return 1;
        }
    }

    if (est->size == est->capacity) {
        est->capacity = (int)(1.618 * est->capacity);
        est->entries = (EnumSymbolTableEntry *)realloc(est->entries, est->capacity * sizeof(EnumSymbolTableEntry));
    }
    est->entries[est->size++] = este;
    
    return 0;
}

EnumSymbolTableEntry * est_lookup(EnumSymbolTable * est, char * name) {
    for (int i = 0; i < est->size; i++) {
        if (!strcmp(est->entries[i].name, name)) {
            return &est->entries[i];
        }
    }
    return NULL;
}
