bash run.sh ../testcases/Phase2_testcases/t1.txt 
bash run.sh ../testcases/Phase2_testcases/t2.txt 
bash run.sh ../testcases/Phase2_testcases/t3.txt 
bash run.sh ../testcases/Phase2_testcases/t4.txt 
bash run.sh ../testcases/Phase2_testcases/t5.txt 
bash run.sh ../testcases/Phase2_testcases/t6.txt 
bash run.sh ../testcases/Phase2_testcases/t7.txt 
bash run.sh ../testcases/Phase2_testcases/t8.txt 
bash run.sh ../testcases/Phase3_testcases/t1.txt 
bash run.sh ../testcases/Phase3_testcases/t2.txt 
bash run.sh ../testcases/Phase3_testcases/t3.txt 
bash run.sh ../testcases/Phase3_testcases/t4.txt 
bash run.sh ../testcases/Phase3_testcases/t5.txt 
bash run.sh ../testcases/Phase3_testcases/t6.txt 
bash run.sh ../testcases/Phase3_testcases/t7.txt 
bash run.sh ../testcases/Phase3_testcases/t8.txt 
bash run.sh ../testcases/Phase4_testcases/t1.txt 
bash run.sh ../testcases/Phase4_testcases/t2.txt 
bash run.sh ../testcases/Phase4_testcases/t3.txt 
bash run.sh ../testcases/Phase4_testcases/t4.txt 
